<?php

return [
    'name' => 'AXORA',
    'city' => 'Libreville, Gabon',
    'email' => 'contact@axora.ga',
    'phone' => '',
    'address' => '',
    'maps_url' => '',
    'hours' => '',
    'history' => "AXORA est une entreprise basée à Libreville, fondée par METCHEBA ILAMBI JOSPIN CARDIS. Elle réunit cinq expertises complémentaires : cybersécurité, data, développement web et mobile, intelligence artificielle et internet des objets. Cette approche permet d'accompagner un projet de son diagnostic à sa mise en œuvre, puis à son suivi.",
    'mission' => 'Sécuriser, connecter et rendre intelligentes les infrastructures numériques de nos clients, avec exigence technique et ancrage local.',
    'vision' => 'Devenir une référence gabonaise et sous-régionale en sécurité numérique et en ingénierie de la donnée.',
    'objectives' => ['Protéger les systèmes et les données des organisations.', 'Créer des outils numériques adaptés aux usages locaux.', 'Transformer les données en décisions utiles.', 'Accompagner les équipes et transmettre les compétences.'],
    'team' => [['name' => 'METCHEBA ILAMBI JOSPIN CARDIS', 'role' => 'Fondateur', 'bio' => '', 'photo_url' => '']],
    'pages' => [
        'home' => [
            'hero_eyebrow' => 'Libreville, Gabon · Solutions numériques',
            'hero_title' => 'Le numérique au service de',
            'hero_emphasis' => 'vos ambitions.',
            'hero_lead' => 'De la sécurité de vos systèmes à la création de vos outils : AXORA accompagne vos projets avec une approche concrète et des expertises complémentaires.',
            'hero_note' => 'Particuliers · Entreprises · Administrations',
            'hero_image' => '', 'story_image' => '',
            'method_eyebrow' => 'De l’idée à l’action',
            'method_title' => 'Un cap clair à chaque étape.',
            'method_intro' => 'Comprendre votre contexte pour construire une réponse qui vous ressemble.',
            'method_steps' => [
                ['number' => '01', 'title' => 'Comprendre', 'text' => 'Échanger sur vos usages, vos contraintes et vos priorités.'],
                ['number' => '02', 'title' => 'Définir', 'text' => 'Cadrer le périmètre, les livrables et les étapes de votre projet.'],
                ['number' => '03', 'title' => 'Construire', 'text' => 'Mettre en œuvre la solution et partager les avancées.'],
                ['number' => '04', 'title' => 'Accompagner', 'text' => 'Transmettre les compétences et faire évoluer vos outils.'],
            ],
            'story_eyebrow' => 'Ancrage local, ambition partagée',
            'story_title' => 'Une relation de travail. Pas seulement une prestation.',
            'story_text' => 'Basée à Libreville, AXORA réunit la cybersécurité, la data, le développement, l’IA et l’IoT pour accompagner vos besoins numériques.',
            'cta_eyebrow' => 'Faisons le premier pas',
            'cta_title' => 'Quel est votre prochain défi ?',
            'cta_text' => 'Un diagnostic, une application ou un système à faire évoluer.',
        ],
        'about' => [
            'eyebrow' => 'À propos d’AXORA', 'title' => 'Une expertise numérique. Un ancrage gabonais.',
            'lead' => 'Accompagner les organisations et les particuliers, du premier besoin à la solution opérationnelle.',
            'story_title' => 'Notre histoire', 'mission_title' => 'Notre mission', 'vision_title' => 'Notre vision',
            'objectives_eyebrow' => 'Ce qui nous guide', 'objectives_title' => 'Nos objectifs',
            'team_eyebrow' => 'Les personnes derrière AXORA', 'team_title' => 'Notre équipe',
            'banner_title' => 'Construisons la suite ensemble.', 'banner_text' => 'Parlons de vos priorités et de votre prochain projet.',
            'image' => '',
        ],
        'contact' => [
            'eyebrow' => 'Contact & localisation', 'title' => 'Votre projet commence par une conversation.',
            'lead' => 'Une question, un besoin précis ou une idée à explorer ? Contactez notre équipe.',
            'needs_title' => 'De quoi avez-vous besoin ?',
        ],
        'footer' => [
            'tagline' => 'Protéger. Construire. Connecter.', 'description' => 'Votre partenaire numérique à Libreville.',
        ],
    ],
];
